### ISSUE TITLE
Use dedicated Sauce user for this project

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs-training/demo-sauce-status-badge#6]
The readme shows a failing badge while in reality the last build was passing. I am not sure about the set up but it seems that the Sauce account used is also being used for other tests. In order to correctly reflect the state for this project I suggest to create a dedicated sub account for this project. What do you think?

**Comment by Tacktician** [comment]
@christian-bromann I created a dedicated user but it looks like the badges aren't rendering correctly on GitHub?

if you check this [url](https://app.saucelabs.com/buildstatus/spider-sauce-tests)  and [this one](https://app.saucelabs.com/browser-matrix/spider-sauce-tests.svg), they displays as expected but on the README the badge isn't working?

Maybe I could try using an html tag outlined [here](https://wiki.saucelabs.com/display/DOCS/Using+Status+Badges+and+the+Browser+Matrix+Widget+to+Monitor+Test+Results#UsingStatusBadgesandtheBrowserMatrixWidgettoMonitorTestResults-SettingUptheBrowserMatrixWidget)?

**Comment by christian-bromann** [comment]
> if you check this [url](https://app.saucelabs.com/buildstatus/spider-sauce-tests) and [this one](https://app.saucelabs.com/browser-matrix/spider-sauce-tests.svg), they displays as expected but on the README the badge isn't working?

Ah, I think this is GitHub caching images that embedded in the readme. I don't think we can do anything here. Thanks for the quick fix!
